[project]
requires-python = ">= 3.9"

[tool.poetry]
name = "wipe_free_space"
version = "1.0.0"
description = "Simple utility for filling unused disk space to prevent deleted file recovery"
authors = [
    "Wiley Black <TheWiley@gmail.com>"
]
readme = "README.md"
packages = [{include = "wipe_free_space"}]

[tool.poetry.dependencies]
python = ">=3.9, <3.14"
numpy = ">= 1.4, <3"
tqdm = ">= 4.66, <5"
psutil = "*"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
coverage = ">=6.3"
flake8 = "^6.0.0"
black = "^22.12"
isort = ">=5.12.0"
mypy = "^1.6.1"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
coverage = ">=6.3"

[tool.poetry.group.deploy.dependencies]
python-semantic-release = ">=9.0.0,<10"
pyinstaller = { version = ">=6.9, <7", python = ">= 3.9" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.black]
line-length = 120

[tool.mypy]
ignore_missing_imports = true

[tool.semantic_release]
assets = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = true
tag_format = "v{version}"
version_variables = [
  "wipe_free_space/__init__.py:__version__"
]
version_toml = [
  "pyproject.toml:tool.poetry.version",
]
dist_path = "dist/"
upload_to_vcs_release = false
upload_to_pypi = false
remove_dist = false
patch_without_tag = true
major_on_zero = true

[tool.semantic_release.changelog]
changelog_file = "CHANGELOG.md"
template_dir = "templates"

[tool.semantic_release.branches.main]
match = "(main)"
prerelease = false

[tool.semantic_release.branches.others]
match = "^(?!main$)"
prerelease = true
prerelease_token = "alpha"

[tool.isort]
src_paths = ["wipe_free_space","tests"]
include_trailing_comma = true
use_parentheses = true
multi_line_output = 3
line_length = 120
skip = [".tox","build"]
known_first_party = "tests"
force_grid_wrap = 0
combine_as_imports = true
